# Generated by Django 6.0.4 on 2026-04-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-date'], name='api_blogpos_date_e6a780_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published'], name='api_blogpos_publish_2cfd99_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='api_blogpos_slug_2bbab2_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-created_at'], name='api_contact_created_b984ff_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['read'], name='api_contact_read_4b2e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-date'], name='api_project_date_5393fe_idx'),
        ),
    ]
